[toolchain]
anchor_version = "0.30.0"
package_manager = "yarn"

[programs.localnet]
vault_ctf = "programs/vault_ctf"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p tsconfig.json -t 1000000 tests/**/*.ts"
